openapi: 3.0.3
info:
  title: VAT Assist (MTD)
  description: |
    # Overview
    Use this API to get HMRC Assist feedback about potential inaccuracies in returns before they are formally submitted.
    You must follow a two-step process:
    1. Send draft return data.
    2. Use the relevant acknowledgement endpoint to confirm that your software has presented the HMRC Assist feedback messages to the user.

    Because this process operates on draft, unfinalised data, requesting feedback carries no formal declaration. Also, the process does not block formal declaration submission via the *returns* endpoint of the [VAT (MTD) API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/). Your software must allow customers to submit their VAT return, irrespective of any HMRC Assist submission feedback.
  contact: {}
  version: '1.0'
servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production
paths:
  /misc/transaction-risking/assist/{vrn}:
    post:
      tags:
        - Endpoints
      summary: Request HMRC Assist feedback for VAT [test only]
      description: |
        Send VAT return data, to receive feedback from HMRC before formally submitting a VAT return. 

        The response will contain feedback messages in English and Welsh, highlighting potential mistakes or discrepancies in the VAT return data.

        **Note:** Before using this endpoint, you must first call the obligations endpoint on the [VAT (MTD) API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/) to get the period key.
        
        ### Test data
        <p>Scenario simulations using Gov-Test-Scenario headers are only available in the sandbox environment.</p>
        <table>
          <thead>
            <tr>
              <th>Header Value (Gov-Test-Scenario)</th>
              <th>Scenario</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><p>Default (No header value)</p></td>
              <td><p>Simulates the scenario where there is one HMRC Assist feedback message.</p></td>
            </tr>
            <tr>
              <td><p>MULTIPLE_FEEDBACK</p></td>
              <td><p>Simulates the scenario where there are more than one HMRC VAT Assist feedback messages.</p></td>
            </tr>
            <tr>
              <td><p>NO_FEEDBACK</p></td>
              <td><p>Simulates the scenario where there is no HMRC VAT Assist feedback.</p></td>
            </tr>
            <tr>
              <td><p>INVALID_VRN</p></td>
              <td><p>Simulates the scenario where the VRN has not passed validation.</p></td>
            </tr>
            <tr>
              <td><p>INVALID_PERIODKEY</p></td>
              <td><p>Simulates the scenario where the periodKey has not passed validation.</p></td>
            </tr>
            <tr>
              <td><p>INVALID_REQUEST</p></td>
              <td><p>Submission has not passed validation. Invalid values.</p></td>
            </tr>
            <tr>
              <td><p>TAX_PERIOD_NOT_ENDED</p></td>
              <td><p>Simulates the scenario where the accounting period has not ended.</p></td>
            </tr>
            <tr>
              <td><p>INSOLVENT_TRADER</p></td>
              <td><p>Simulates the scenario where the client is an insolvent trader.</p></td>
            </tr>
          </tbody>
        </table>

      operationId: RequestVATAssistFeedback
      parameters:
        - name: vrn
          in: path
          description: |
            VAT registration number. <br> A nine-digit number.
          required: true
          style: simple
          schema:
            type: string
            pattern: '^[0-9]{9}$'
            example: '123456789'
        - name: Gov-Test-Scenario
          in: header
          description: Only in sandbox environment. See Test Data table for all header values.
          style: simple
          schema:
            type: string
            example: '-'
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/authorizationWriteScopeHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/VATAssistRequest'
                - example:
                    periodKey: '18AD'
                    vatDueSales: 105.50
                    vatDueAcquisitions: 0.00
                    totalVatDue: 105.50
                    vatReclaimedCurrPeriod: 52.75
                    netVatDue: 52.75
                    totalValueSalesExVAT: 500
                    totalValuePurchasesExVAT: 250
                    totalValueGoodsSuppliedExVAT: 0
                    totalAcquisitionsExVAT: 0
      responses:
        '200':
          description: Feedback returned successfully.
          headers:
            X-CorrelationId:
              description: Unique ID for operation tracking. String, 36 characters.
              content:
                text/plain:
                  schema:
                    type: string
                    example: c75f40a6-a3df-4429-a697-471eeec46435
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VATAssistResponse'
              examples:
                "Example 1 (single feedback message)":
                  description: |
                    The scenario where there is one HMRC Assist feedback message.

                    Note that the feedback message in this example is for illustration purposes only. Actual feedback messages may differ.
                  value:
                    reportId: 'f2fb30e5-4ab6-4a29-b3c1-c00000000001'
                    correlationId: 'E9F65715BBC9222477B27074804BBDD5C73CDE62F84D8B00CFD05B883534AF3D'
                    englishFeedback:
                      - itemNumber: '1'
                        title: 'HMRC feedback: VAT due on sales appears low'
                        body: 'The VAT due on sales figure appears lower than expected based on your total sales value.'
                        action: 'Please review box 1 and box 6 of your VAT return.'
                        links:
                          - title: 'VAT Notice 700'
                            url: 'https://www.gov.uk/guidance/vat-notice-700-the-vat-guide'
                        path: 'vatDueSales'
                    welshFeedback:
                      - itemNumber: '1'
                        title: 'Mae TAW sy''n ddyledus ar werthiannau yn ymddangos yn isel'
                        body: 'Mae''r ffigur TAW sy''n ddyledus ar werthiannau yn ymddangos yn is na''r disgwyl yn seiliedig ar gyfanswm eich gwerthiannau.'
                        action: 'Adolygwch flwch 1 a blwch 6 eich ffurflen TAW.'
                        links:
                          - title: 'Hysbysiad TAW 700'
                            url: 'https://www.gov.uk/guidance/vat-notice-700-the-vat-guide'
                        path: 'vatDueSales'
                "Example 2 (multiple feedback messages)":
                  description: |
                    The scenario where there are multiple HMRC Assist feedback messages.

                    Note that the feedback messages in this example are for illustration purposes only. Actual feedback messages may differ.
                  value:
                    reportId: 'f2fb30e5-4ab6-4a29-b3c1-c00000000001'
                    correlationId: 'E9F65715BBC9222477B27074804BBDD5C73CDE62F84D8B00CFD05B883534AF3D'
                    englishFeedback:
                      - itemNumber: '1'
                        title: 'HMRC feedback: VAT due on sales appears low'
                        body: 'The VAT due on sales figure appears lower than expected based on your total sales value.'
                        action: 'Please review box 1 and box 6 of your VAT return.'
                        links:
                          - title: 'VAT Notice 700'
                            url: 'https://www.gov.uk/guidance/vat-notice-700-the-vat-guide'
                        path: 'vatDueSales'
                      - itemNumber: '2'
                        title: 'Total value of purchases appears high'
                        body: 'The total value of purchases appears higher than expected based on your total sales value.'
                        action: 'Please review box 7 of your VAT return.'
                        links:
                          - title: 'VAT Notice 700'
                            url: 'https://www.gov.uk/guidance/vat-notice-700-the-vat-guide'
                        path: 'totalValuePurchasesExVAT'
                    welshFeedback:
                      - itemNumber: '1'
                        title: 'Mae TAW sy''n ddyledus ar werthiannau yn ymddangos yn isel'
                        body: 'Mae''r ffigur TAW sy''n ddyledus ar werthiannau yn ymddangos yn is na''r disgwyl yn seiliedig ar gyfanswm eich gwerthiannau.'
                        action: 'Adolygwch flwch 1 a blwch 6 eich ffurflen TAW.'
                        links:
                          - title: 'Hysbysiad TAW 700'
                            url: 'https://www.gov.uk/guidance/vat-notice-700-the-vat-guide'
                        path: 'vatDueSales'
                      - itemNumber: '2'
                        title: 'Mae cyfanswm pryniannau''n uchel'
                        body: 'Mae cyfanswm y pryniannau''n ymddangos yn uwch na''r disgwyl.'
                        action: 'Adolygwch flwch 7 o''ch ffurflen TAW.'
                        links:
                          - title: 'Hysbysiad TAW 700'
                            url: 'https://www.gov.uk/guidance/vat-notice-700-the-vat-guide'
                        path: 'totalValuePurchasesExVAT'
                "Example 3 (no feedback)":
                  description: |
                    The scenario where there is no HMRC Assist feedback.

                    Note that the message in this example is for illustration purposes only.
                  value:
                    reportId: 'f2fb30e5-4ab6-4a29-b3c1-c00000000001'
                    correlationId: 'E9F65715BBC9222477B27074804BBDD5C73CDE62F84D8B00CFD05B883534AF3D'
                    englishFeedback:
                      - itemNumber: '0'
                        title: 'HMRC feedback: HMRC Assist has not returned any messages.'
                        body: 'This is not a complete check of your return or confirmation that your return is accurate. Your return has
                               not been submitted at this stage.'
                        action: 'Consider any further checks before finalising your return.'
                        links:
                          - title: 'Go to GOV.UK for more information on HMRC Assist'
                            url: 'https://www.gov.uk'
                    welshFeedback:
                      - itemNumber: '0'
                        title: 'Nid yw HMRC Assist wedi dychwelyd unrhyw negeseuon.'
                        body: 'Nid yw hwn yn wiriad cyflawn o''ch datganiad nac yn gadarnhad bod 
                               eich datganiad yn gywir. Nid yw eich datganiad wedi''i gyflwyno ar y cam hwn.'
                        action: 'Ystyriwch unrhyw wiriadau pellach cyn cwblhau eich datganiad.'
                        links:
                          - title: 'Ewch i GOV.UK am ragor o wybodaeth am HMRC Assist'
                            url: 'https://www.gov.uk'
        '400':
          description: Bad request. Invalid request body or parameters.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorResponse'
                  -  example:
                       code: 'INVALID_VRN'
                       message: 'The provided VRN is invalid.'
              examples:
                invalidVrn:
                  description: Invalid VRN
                  value:
                    code: VRN_INVALID
                    message: The provided VRN is invalid
                invalidPeriodKey:
                  description: Invalid period key
                  value:
                    code: PERIOD_KEY_INVALID
                    message: Invalid period key
                invalidRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
                    message: Invalid request
                invalidTotalValue:
                  description: totalVatDue should be equal to the sum of vatDueSales and vatDueAcquisitions
                  value:
                    code: VAT_TOTAL_VALUE
                    message: totalVatDue should be equal to the sum of vatDueSales and vatDueAcquisitions
                invalidNetValue:
                  description: netVatDue should be the difference between the largest and the smallest values among totalVatDue and vatReclaimedCurrPeriod
                  value:
                    code: VAT_NET_VALUE
                    message: netVatDue should be the difference between the largest and the smallest values among totalVatDue and vatReclaimedCurrPeriod
                invalidNumericValue:
                  description: Please provide a numeric field
                  value:
                    code: INVALID_NUMERIC_VALUE
                    message: please provide a numeric field
                invalidMonetaryAmount:
                  description: The monetary amount is invalid
                  value:
                    code: INVALID_MONETARY_AMOUNT
                    message: amount should be a monetary value (to 2 decimal places), between 0 and 99,999,999,999.99
        '403':
          description: Forbidden. The client is not authorised to access this resource.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorResponse'
                  - example:
                      code: 'CLIENT_OR_AGENT_NOT_AUTHORISED'
                      message: 'The client and/or agent is not authorised.'
              examples:
                submittedTooEarly:
                  description: Return submitted too early
                  value:
                    code: TAX_PERIOD_NOT_ENDED
                    message: The remote endpoint has indicated that the submission is for a tax period that has not ended
                clientNotSubscribedToMTD:
                  description: 'The client and/or agent is not authorised. This is normally because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                  value:
                    code: CLIENT_OR_AGENT_NOT_AUTHORISED
                    message: The client and/or agent is not authorised
                ruleInsolventTrader:
                  description: The request could not be completed as it relates to an insolvent trader, which are not supported by this API.
                  value:
                    code: RULE_INSOLVENT_TRADER
                    message: The remote endpoint has indicated that the Trader is insolvent
        '404':
          description: Not found. The VRN could not be found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 'VRN_NOT_FOUND'
                message: 'The remote endpoint has indicated that the VRN could not be found.'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 'INTERNAL_SERVER_ERROR'
                message: 'An unexpected error occurred.'
      security:
        - userRestricted:
            - write:vat

  /misc/transaction-risking/acknowledge/{vrn}/{reportId}/{correlationId}:
    post:
      tags:
        - Endpoints
      summary: Acknowledge HMRC Assist for VAT feedback [test only]
      description: |
        Acknowledge an HMRC Assist for VAT report, and confirm that your software has presented the feedback messages verbatim to the user.

        ### Test data
        <p>Scenario simulations using Gov-Test-Scenario headers are only available in the sandbox environment.</p>
        <table>
          <thead>
            <tr>
              <th>Header Value (Gov-Test-Scenario)</th>
              <th>Scenario</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><p>Default (No header value)</p></td>
              <td><p>Acknowledgement received.</p></td>
            </tr>
            <tr>
              <td><p>INVALID_VRN</p></td>
              <td><p>Scenario where the VRN has not passed validation.</p></td>
            </tr>
            <tr>
              <td><p>INVALID_REPORTID</p></td>
              <td><p>Scenario where the reportId has not passed validation.</p></td>
            </tr>
            <tr>
              <td><p>INVALID_DATETIME</p></td>
              <td><p>Scenario where the presented DateTime has not passed validation.</p></td>
            </tr>
            <tr>
              <td><p>INVALID_CREDENTIALS</p></td>
              <td><p>Scenario where invalid authentication information is provided.</p></td>
            </tr>
            <tr>
              <td><p>NOT_AUTHORISED</p></td>
              <td><p>Scenario where the client or their agent is not authorised.</p></td>
            </tr>
            <tr>
              <td><p>CORRELATION_ID</p></td>
              <td><p>Scenario where the correlation ID does not match.</p></td>
            </tr>
            <tr>
              <td><p>NOT_FOUND</p></td>
              <td><p>Simulates the scenario where the report cannot be found.</p></td>
            </tr>
          </tbody>
        </table>

      operationId: AcknowledgeVATAssistReport
      parameters:
        - name: vrn
          in: path
          description: |
            VAT registration number. <br> A nine-digit number.
          required: true
          style: simple
          schema:
            type: string
            pattern: '^[0-9]{9}$'
            example: '123456789'
        - name: reportId
          in: path
          description: The unique identifier for the report.
          required: true
          style: simple
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'
            example: 'f2fb30e5-4ab6-4a29-b3c1-c00000000001'
        - name: correlationId
          in: path
          description: The correlation ID of the report.
          required: true
          style: simple
          schema:
            type: string
            example: 'E9F65715BBC9222477B27074804BBDD5C73CDE62F84D8B00CFD05B883534AF3D'
        - name: presentedDateTime
          in: query
          description: The date and time (in Z/UTC) that the feedback was presented verbatim to the user.
          required: true
          style: form
          explode: true
          schema:
            type: string
            format: date-time
            example: '2026-06-09T10:30:00Z'
        - name: Gov-Test-Scenario
          in: header
          description: Only in sandbox environment. See Test Data table for all header values.
          style: simple
          schema:
            type: string
            example: '-'
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/authorizationWriteScopeHeader'
      responses:
        '204':
          description: Acknowledgement recorded successfully. No content returned.
          headers:
            X-CorrelationId:
              description: Unique ID for operation tracking. String, 36 characters.
              content:
                text/plain:
                  schema:
                    type: string
                    pattern: '^[A-Za-z0-9\-]{36}$'
                    example: 'a1e8057e-fbbc-47a8-a8b4-78d9f015c253'
        '400':
          description: Bad request. Invalid request parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                VRN_INVALID:
                  summary: Invalid VRN
                  value:
                    code: 'VRN_INVALID'
                    message: 'The provided VRN is invalid.'
                FORMAT_REPORT_ID:
                  summary: Invalid Report ID
                  value:
                    code: 'FORMAT_REPORT_ID'
                    message: 'The provided Report ID is invalid.'
                FORMAT_DATETIME:
                  summary: Invalid presentedDateTime
                  value:
                    code: 'FORMAT_DATETIME'
                    message: 'The provided Presented Date Time is invalid.'
        '401':
          description: Unauthorised. Invalid authentication information provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 'INVALID_CREDENTIALS'
                message: 'Invalid authentication information provided.'
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                CLIENT_OR_AGENT_NOT_AUTHORISED:
                  summary: Client and/or agent not authorised
                  value:
                    code: 'CLIENT_OR_AGENT_NOT_AUTHORISED'
                    message: 'Client and/or agent is not authorised.'
                CORRELATION_ID:
                  summary: Mismatching correlation ID
                  value:
                    code: 'CORRELATION_ID'
                    message: 'The Correlation ID is not the expected value for this report.'
        '404':
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 'MATCHING_RESOURCE_NOT_FOUND'
                message: 'A resource with the name in the request can not be found in the API.'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 'INTERNAL_SERVER_ERROR'
                message: 'An unexpected error occurred.'
      security:
        - userRestricted:
            - write:vat

components:
  parameters:
    acceptHeader:
      name: "Accept"
      in: header
      description: |
        Specifies the response format and the version of the API to be used.
      schema:
        type: string
        enum:
          - "application/vnd.hmrc.1.0+json"
      required: true
    authorizationWriteScopeHeader:
      name: "Authorization"
      in: header
      description: |
        An OAuth 2.0 Bearer Token with the *write:vat* scope.
      schema:
        type: string
        example: Bearer bb7fed3fe10dd235a2ccda3d50fb
      required: true
  schemas:
    VATAssistRequest:
      title: VATAssistRequest
      required:
        - periodKey
        - vatDueSales
        - vatDueAcquisitions
        - totalVatDue
        - vatReclaimedCurrPeriod
        - netVatDue
        - totalValueSalesExVAT
        - totalValuePurchasesExVAT
        - totalValueGoodsSuppliedExVAT
        - totalAcquisitionsExVAT
      type: object
      properties:
        periodKey:
          type: string
          minLength: 4
          maxLength: 4
          pattern: '^[#0-9A-Z]{4}$'
          description: >
            The ID code for the period that this obligation belongs to.
            This should be obtained from the obligations endpoint of the [VAT (MTD) API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/).
            The format is a string of four alphanumeric characters.
            Occasionally the format includes the # symbol.
          example: '18AD'
        vatDueSales:
          type: number
          multipleOf: 0.01
          minimum: -9999999999999.99
          maximum: 9999999999999.99
          description: >
            VAT due on sales and other outputs. This corresponds to box 1
            on the VAT Return form.
          example: 105.50
        vatDueAcquisitions:
          type: number
          multipleOf: 0.01
          minimum: -9999999999999.99
          maximum: 9999999999999.99
          description: >
            VAT due in the period on acquisitions of goods made in Northern
            Ireland from EU Member States. This corresponds to box 2 on the
            VAT Return form.
          example: 0.00
        totalVatDue:
          type: number
          multipleOf: 0.01
          minimum: -9999999999999.99
          maximum: 9999999999999.99
          description: >
            Total VAT due (the sum of vatDueSales and vatDueAcquisitions).
            This corresponds to box 3 on the VAT Return form.
          example: 105.50
        vatReclaimedCurrPeriod:
          type: number
          multipleOf: 0.01
          minimum: -9999999999999.99
          maximum: 9999999999999.99
          description: >
            VAT reclaimed in the period on purchases and other inputs
            (including acquisitions in Northern Ireland from EU member states).
            This corresponds to box 4 on the VAT Return form.
          example: 52.75
        netVatDue:
          type: number
          multipleOf: 0.01
          minimum: 0.00
          maximum: 99999999999.99
          description: |
            The absolute difference between the *totalVatDue* and
            *vatReclaimedCurrPeriod* values. This should therefore be a positive
            number, calculated by subtracting the smallest value from the
            largest. HMRC will automatically determine whether the number
            represents net VAT that is due or net VAT that can be reclaimed.

            This corresponds to box 5 on the VAT Return form.
          example: 52.75
        totalValueSalesExVAT:
          type: number
          minimum: -9999999999999
          maximum: 9999999999999
          description: >
            Total value of sales and all other outputs excluding any VAT.
            This corresponds to box 6 on the VAT Return form.
            The value must be in whole pounds (no pence).
          example: 500
        totalValuePurchasesExVAT:
          type: number
          minimum: -9999999999999
          maximum: 9999999999999
          description: >
            Total value of purchases and all other inputs excluding any VAT
            (including exempt purchases). This corresponds to box 7 on the
            VAT Return form. The value must be in whole pounds (no pence).
          example: 250
        totalValueGoodsSuppliedExVAT:
          type: number
          minimum: -9999999999999
          maximum: 9999999999999
          description: >
            Total value of dispatches of goods and related costs (excluding VAT)
            from Northern Ireland to EU Member States. This corresponds to box 8
            on the VAT Return form. The value must be in whole pounds (no pence).
          example: 0
        totalAcquisitionsExVAT:
          type: number
          minimum: -9999999999999
          maximum: 9999999999999
          description: >
            Total value of acquisitions of goods and related costs (excluding VAT)
            made in Northern Ireland from EU Member States. This corresponds to
            box 9 on the VAT Return form. The value must be in whole pounds (no pence).
          example: 0

    VATAssistResponse:
      title: VATAssistResponse
      required:
        - reportId
        - correlationId
        - englishFeedback
        - welshFeedback
      type: object
      properties:
        reportId:
          type: string
          pattern: '^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'
          description: The unique identifier for the report.
          example: 'f2fb30e5-4ab6-4a29-b3c1-c00000000001'
        correlationId:
          type: string
          description: The correlation ID of the report.
          example: 'E9F65715BBC9222477B27074804BBDD5C73CDE62F84D8B00CFD05B883534AF3D'
        englishFeedback:
          type: array
          description: |
            An array that contains up to 5 HMRC Assist feedback messages, in English.

            The total number of characters across all text fields in an individual message will not exceed 32767.
          items:
            $ref: '#/components/schemas/FeedbackItem'
        welshFeedback:
          type: array
          description: |
            An array that contains up to 5 HMRC Assist feedback messages, in Welsh.

            The total number of characters across all text fields in an individual message will not exceed 32767.
          items:
            $ref: '#/components/schemas/FeedbackItem'

    FeedbackItem:
      title: FeedbackItem
      required:
        - itemNumber
        - title
        - body
      type: object
      properties:
        itemNumber:
          type: string
          pattern: '^[0-9]{3}$'
          description: The unique identifier for the feedback message. Corresponding English and Welsh feedback messages will have the same number.
          example: '1'
        title:
          type: string
          maxLength: 32767
          description: The title of the feedback message. It tells the user to review or check something in the return.
          example: 'VAT due on sales appears low'
        body:
          type: string
          maxLength: 32767
          description: The main body of the feedback message, which is an explanation that usually consists of three or four sentences.
          example: 'The VAT due on sales figure appears lower than expected based on your total sales value.'
        action:
          type: string
          maxLength: 32767
          description: The recommended action (if any) that the customer should take to address the issue described in the feedback message.
          example: 'Please review box 1 and box 6 of your VAT return.'
        links:
          type: array
          description: A list of links to any supporting information that relates to the feedback message.
          items:
            $ref: '#/components/schemas/FeedbackLink'
        path:
          type: string
          maxLength: 32767
          description: The VAT box numbers and equivalent descriptions (as appearing on a paper return) that are the focus of the feedback presented in the message.
          example: 'vatDueSales'

    FeedbackLink:
      title: FeedbackLink
      type: object
      properties:
        title:
          type: string
          maxLength: 32767
          description: The title or brief description of the supporting information.
          example: 'VAT Notice 700'
        url:
          type: string
          maxLength: 32767
          description: The URL of the supporting information.
          example: 'https://www.gov.uk/guidance/vat-notice-700-the-vat-guide'

    ErrorResponse:
      title: ErrorResponse
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
          description: The error code.
          example: 'INVALID_VRN'
        message:
          type: string
          description: A human-readable description of the error.
          example: 'The provided VRN is invalid.'

  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests
        using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:vat: Grant write access to VAT data
            read:vat: Grant read access to VAT data

tags:
  - name: Endpoints
    description: ''
